version: '3.5'
services:
  python_etl_img:
    container_name: etl_python_container
    depends_on:
      - mongo
    build:
      context: .
    volumes:
      - ./src:/srv/app/
    networks:
      etl-network:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xxxxxx
    networks:
      etl-network:
networks:
  etl-network:
